# SPDX-FileCopyrightInfo: Copyright © DUNE Project contributors, see file LICENSE.md in module root
# SPDX-License-Identifier: LGPL-3.0-or-later OR LicenseRef-GPL-2.0-only-with-dune-grid-glue-exception

---
.common: &common
  script: duneci-standard-test
  artifacts:
    expire_in: 2 years
    reports:
      junit: junit/*.xml
  tags: [duneci]

dune:git gcc-8 C++17:
  <<: *common
  image: registry.dune-project.org/docker/ci/dune:git-debian-10-gcc-8-17

dune:git gcc-9 C++20:
  <<: *common
  image: registry.dune-project.org/docker/ci/dune:git-debian-11-gcc-9-20

dune:git  clang  C++17:
  <<: *common
  image: registry.dune-project.org/docker/ci/dune:git-debian-10-clang-7-libcpp-17

dune:2.8 gcc-9 C++20:
  <<: *common
  image: registry.dune-project.org/docker/ci/dune:2.8-debian-11-gcc-9-20

dune:2.7 gcc-8 C++17:
  <<: *common
  image: registry.dune-project.org/docker/ci/dune:2.7-debian-10-gcc-8-17

reuse:
  stage: .pre
  image:
    name: docker.io/fsfe/reuse:latest
    entrypoint: [""]
  tags: [duneci]
  before_script: ""
  script:
    - reuse lint
