# SPDX-FileCopyrightInfo: Copyright © DUNE Project contributors, see file LICENSE.md in module root
# SPDX-License-Identifier: LGPL-3.0-or-later OR LicenseRef-GPL-2.0-only-with-dune-grid-glue-exception

#dune module information file#
##############################

#Name of the module
Module: dune-grid-glue
Version: 2.10
Maintainer: christian.engwer@uni-muenster.de,oliver.sander@tu-dresden.de
#depending on
Depends: dune-common (>= 2.7) dune-geometry (>= 2.7) dune-grid (>= 2.7)
Whitespace-Hook: Yes
